[tool.poetry]
name = "fastapi-oidc"
version = "0.0.2"
description = "A simple library for parsing and verifying externally issued OIDC ID tokens in fastapi."
authors = ["HarryMWinters <harrymcwinters@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.8"
fastapi = "^0.61.0"

[tool.poetry.dev-dependencies]
pytest = "^6.0.1"
black = "^19.10b0"
pylint = "^2.6.0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
